# Generated by Django 4.2.10 on 2024-08-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=10, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
